<?php

// Explicit resource and field allowlist for the Inertia admin.
return ['peserta' => ['model' => 'User',
    'title' => 'Peserta',
    'group' => 'Utama',
    'fields' => [['name' => 'name',
        'label' => 'Nama lengkap',
        'type' => 'text',
        'required' => true,
        'max' => 100], ['name' => 'email',
            'label' => 'Email',
            'type' => 'email',
            'required' => true,
            'max' => 100,
            'unique' => true], ['name' => 'password',
                'label' => 'Password',
                'type' => 'password',
                'required' => false], ['name' => 'nip',
                    'label' => 'Nip',
                    'type' => 'text',
                    'required' => false,
                    'unique' => true], ['name' => 'no_hp',
                        'label' => 'No hp',
                        'type' => 'text',
                        'required' => false,
                        'max' => 30], ['name' => 'kode_user',
                            'label' => 'Kode user',
                            'type' => 'text',
                            'required' => false,
                            'unique' => true], ['name' => 'jenis_user_id',
                                'label' => 'Jenis pengguna',
                                'type' => 'reference',
                                'required' => true,
                                'model' => 'JenisUser',
                                'labelColumn' => 'nama_jenis'], ['name' => 'struktur_id',
                                    'label' => 'Struktur',
                                    'type' => 'reference',
                                    'required' => false,
                                    'model' => 'Struktur',
                                    'labelColumn' => 'nama_struktur'], ['name' => 'jenis_kelamin',
                                        'label' => 'Jenis kelamin',
                                        'type' => 'select',
                                        'required' => true,
                                        'options' => [['value' => 'L',
                                            'label' => 'L'], ['value' => 'P',
                                                'label' => 'P']]], ['name' => 'pekerjaan',
                                                    'label' => 'Pekerjaan',
                                                    'type' => 'text',
                                                    'required' => false], ['name' => 'kota',
                                                        'label' => 'Kota',
                                                        'type' => 'text',
                                                        'required' => false,
                                                        'max' => 50], ['name' => 'kategori',
                                                            'label' => 'Status',
                                                            'type' => 'select',
                                                            'required' => false,
                                                            'options' => [['value' => 'Aktif',
                                                                'label' => 'Aktif'], ['value' => 'Tidak Aktif',
                                                                    'label' => 'Tidak Aktif'], ['value' => 'Keluar',
                                                                        'label' => 'Keluar']]], ['name' => 'gelombang_id',
                                                                            'label' => 'Gelombang',
                                                                            'type' => 'reference',
                                                                            'required' => true,
                                                                            'model' => 'Gelombang',
                                                                            'labelColumn' => 'gel'], ['name' => 'valid_email',
                                                                                'label' => 'Valid email',
                                                                                'type' => 'checkbox',
                                                                                'required' => false,
                                                                                'default' => true], ['name' => 'catatan',
                                                                                    'label' => 'Catatan',
                                                                                    'type' => 'textarea',
                                                                                    'required' => false]],
    'columns' => ['name', 'email', 'gelombang_id', 'kategori', 'jenis_user_id'],
    'relations' => ['groups' => ['Group', 'nama_group'],
        'roadmaps' => ['Roadmap', 'nama_roadmap']]],
    'materi' => ['model' => 'Materi',
        'title' => 'Materi',
        'group' => 'Pembelajaran',
        'fields' => [['name' => 'nama_materi',
            'label' => 'Nama materi',
            'type' => 'text',
            'required' => true], ['name' => 'kode_materi',
                'label' => 'Kode materi',
                'type' => 'text',
                'required' => false,
                'unique' => true], ['name' => 'urutan',
                    'label' => 'Urutan',
                    'type' => 'number',
                    'required' => true], ['name' => 'kategori_id',
                        'label' => 'Kategori',
                        'type' => 'reference',
                        'required' => true,
                        'model' => 'KategoriMateri',
                        'labelColumn' => 'nama_kategori'], ['name' => 'materi_per_pekan',
                            'label' => 'Materi per pekan',
                            'type' => 'number',
                            'required' => true,
                            'min' => 1,
                            'max' => 6,
                            'default' => 2], ['name' => 'sertifikat_id',
                                'label' => 'Template sertifikat',
                                'type' => 'reference',
                                'required' => true,
                                'model' => 'Sertifikat',
                                'labelColumn' => 'nama'], ['name' => 'sinopsis',
                                    'label' => 'Sinopsis',
                                    'type' => 'textarea',
                                    'required' => true], ['name' => 'is_active',
                                        'label' => 'Is active',
                                        'type' => 'checkbox',
                                        'required' => false,
                                        'default' => true], ['name' => 'kelas_intensif',
                                            'label' => 'Kelas intensif',
                                            'type' => 'checkbox',
                                            'required' => false,
                                            'default' => true]],
        'columns' => ['nama_materi', 'kode_materi', 'kategori_id', 'materi_per_pekan', 'is_active']],
    'pertemuan' => ['model' => 'MateriDetail',
        'title' => 'Pertemuan',
        'group' => 'Pembelajaran',
        'fields' => [['name' => 'materi_id',
            'label' => 'Materi',
            'type' => 'reference',
            'required' => true,
            'model' => 'Materi',
            'labelColumn' => 'nama_materi'], ['name' => 'pertemuan',
                'label' => 'Pertemuan',
                'type' => 'number',
                'required' => true], ['name' => 'judul',
                    'label' => 'Judul',
                    'type' => 'text',
                    'required' => true,
                    'max' => 100], ['name' => 'jenis_kontent',
                        'label' => 'Jenis kontent',
                        'type' => 'select',
                        'required' => true,
                        'options' => [['value' => 'Audio',
                            'label' => 'Audio'], ['value' => 'Video',
                                'label' => 'Video'], ['value' => 'Text',
                                    'label' => 'Text']]], ['name' => 'multimedia_url',
                                        'label' => 'Berkas audio',
                                        'type' => 'file',
                                        'required' => false,
                                        'accept' => 'audio/*'], ['name' => 'video_url',
                                            'label' => 'Video url',
                                            'type' => 'url',
                                            'required' => false], ['name' => 'isi',
                                                'label' => 'Isi',
                                                'type' => 'textarea',
                                                'required' => false]],
        'columns' => ['materi_id', 'pertemuan', 'judul', 'jenis_kontent', 'video_url']],
    'soal' => ['model' => 'Soal',
        'title' => 'Bank Soal',
        'group' => 'Pembelajaran',
        'fields' => [['name' => 'materi_id',
            'label' => 'Materi',
            'type' => 'reference',
            'required' => true,
            'model' => 'Materi',
            'labelColumn' => 'nama_materi'], ['name' => 'materi_detail_id',
                'label' => 'Pertemuan',
                'type' => 'reference',
                'required' => false,
                'model' => 'MateriDetail',
                'labelColumn' => 'judul'], ['name' => 'jenis_ujian_id',
                    'label' => 'Jenis ujian',
                    'type' => 'reference',
                    'required' => true,
                    'model' => 'JenisUjian',
                    'labelColumn' => 'nama'], ['name' => 'urutan',
                        'label' => 'Urutan',
                        'type' => 'number',
                        'required' => true], ['name' => 'pekan',
                            'label' => 'Pekan',
                            'type' => 'number',
                            'required' => false], ['name' => 'nomor',
                                'label' => 'Nomor',
                                'type' => 'number',
                                'required' => true], ['name' => 'judul',
                                    'label' => 'Soal',
                                    'type' => 'text',
                                    'required' => true], ['name' => 'detail',
                                        'label' => 'Detail',
                                        'type' => 'textarea',
                                        'required' => false], ['name' => 'a',
                                            'label' => 'Jawaban A',
                                            'type' => 'text',
                                            'required' => true], ['name' => 'b',
                                                'label' => 'Jawaban B',
                                                'type' => 'text',
                                                'required' => true], ['name' => 'c',
                                                    'label' => 'Jawaban C',
                                                    'type' => 'text',
                                                    'required' => false], ['name' => 'd',
                                                        'label' => 'Jawaban D',
                                                        'type' => 'text',
                                                        'required' => false], ['name' => 'kunci',
                                                            'label' => 'Kunci jawaban',
                                                            'type' => 'select',
                                                            'required' => true,
                                                            'options' => [['value' => 'a',
                                                                'label' => 'a'], ['value' => 'b',
                                                                    'label' => 'b'], ['value' => 'c',
                                                                        'label' => 'c'], ['value' => 'd',
                                                                            'label' => 'd']]]],
        'columns' => ['judul', 'materi_id', 'jenis_ujian_id', 'nomor', 'kunci']],
    'roadmap' => ['model' => 'Roadmap',
        'title' => 'Roadmap',
        'group' => 'Pembelajaran',
        'fields' => [['name' => 'nama_roadmap',
            'label' => 'Nama roadmap',
            'type' => 'text',
            'required' => true,
            'max' => 191], ['name' => 'detail',
                'label' => 'Detail',
                'type' => 'textarea',
                'required' => false]],
        'columns' => ['nama_roadmap'],
        'relations' => ['materi' => ['Materi', 'nama_materi'],
            'gelombangs' => ['Gelombang', 'gel']]],
    'gelombang' => ['model' => 'Gelombang',
        'title' => 'Gelombang',
        'group' => 'Pembelajaran',
        'fields' => [['name' => 'gel',
            'label' => 'Nama gelombang',
            'type' => 'text',
            'required' => true,
            'max' => 191], ['name' => 'tanggal_mulai',
                'label' => 'Tanggal mulai',
                'type' => 'date',
                'required' => true]],
        'columns' => ['gel', 'tanggal_mulai'],
        'relations' => ['roadmaps' => ['Roadmap', 'nama_roadmap']]],
    'angkatan' => ['model' => 'Angkatan',
        'title' => 'Angkatan',
        'group' => 'Pembelajaran',
        'fields' => [['name' => 'kode_angkatan',
            'label' => 'Kode angkatan',
            'type' => 'text',
            'required' => true,
            'unique' => true], ['name' => 'materi_id',
                'label' => 'Materi',
                'type' => 'reference',
                'required' => true,
                'model' => 'Materi',
                'labelColumn' => 'nama_materi'], ['name' => 'mulai_pendaftaran',
                    'label' => 'Mulai pendaftaran',
                    'type' => 'date',
                    'required' => true], ['name' => 'akhir_pendaftaran',
                        'label' => 'Akhir pendaftaran',
                        'type' => 'date',
                        'required' => true], ['name' => 'kuota',
                            'label' => 'Kuota',
                            'type' => 'number',
                            'required' => true,
                            'default' => 1000], ['name' => 'tanggal_mulai',
                                'label' => 'Tanggal mulai',
                                'type' => 'date',
                                'required' => true], ['name' => 'tanggal_ujian',
                                    'label' => 'Tanggal ujian',
                                    'type' => 'date',
                                    'required' => true], ['name' => 'tanggal_akhir',
                                        'label' => 'Tanggal akhir',
                                        'type' => 'date',
                                        'required' => true], ['name' => 'sertifikat_id',
                                            'label' => 'Template sertifikat',
                                            'type' => 'reference',
                                            'required' => true,
                                            'model' => 'Sertifikat',
                                            'labelColumn' => 'nama'], ['name' => 'gelombang_id',
                                                'label' => 'Gelombang',
                                                'type' => 'reference',
                                                'required' => true,
                                                'model' => 'Gelombang',
                                                'labelColumn' => 'gel'], ['name' => 'status',
                                                    'label' => 'Status',
                                                    'type' => 'select',
                                                    'required' => true,
                                                    'options' => [['value' => 'Persiapan',
                                                        'label' => 'Persiapan'], ['value' => 'Pendaftaran',
                                                            'label' => 'Pendaftaran'], ['value' => 'Full',
                                                                'label' => 'Full'], ['value' => 'Aktif',
                                                                    'label' => 'Aktif'], ['value' => 'Selesai',
                                                                        'label' => 'Selesai']]], ['name' => 'is_umum',
                                                                            'label' => 'Is umum',
                                                                            'type' => 'checkbox',
                                                                            'required' => false,
                                                                            'default' => true], ['name' => 'fb_pixel_id',
                                                                                'label' => 'Fb pixel id',
                                                                                'type' => 'text',
                                                                                'required' => false]],
        'columns' => ['kode_angkatan', 'materi_id', 'gelombang_id', 'tanggal_mulai', 'status']],
    'jadwal-belajar' => ['model' => 'Belajar',
        'title' => 'Jadwal Belajar',
        'group' => 'Pembelajaran',
        'fields' => [['name' => 'materi_detail_id',
            'label' => 'Pertemuan',
            'type' => 'reference',
            'required' => true,
            'model' => 'MateriDetail',
            'labelColumn' => 'judul'], ['name' => 'user_id',
                'label' => 'Peserta',
                'type' => 'reference',
                'required' => false,
                'model' => 'User',
                'labelColumn' => 'name'], ['name' => 'tanggal',
                    'label' => 'Tanggal',
                    'type' => 'date',
                    'required' => true], ['name' => 'status',
                        'label' => 'Status',
                        'type' => 'select',
                        'required' => true,
                        'options' => [['value' => 'Berikutnya',
                            'label' => 'Berikutnya'], ['value' => 'Sekarang',
                                'label' => 'Sekarang'], ['value' => 'Selesai',
                                    'label' => 'Selesai'], ['value' => 'Expired',
                                        'label' => 'Expired']]], ['name' => 'angkatan_id',
                                            'label' => 'Angkatan',
                                            'type' => 'reference',
                                            'required' => false,
                                            'model' => 'Angkatan',
                                            'labelColumn' => 'kode_angkatan'], ['name' => 'gelombang_id',
                                                'label' => 'Gelombang',
                                                'type' => 'reference',
                                                'required' => false,
                                                'model' => 'Gelombang',
                                                'labelColumn' => 'gel'], ['name' => 'roadmap_id',
                                                    'label' => 'Roadmap',
                                                    'type' => 'reference',
                                                    'required' => false,
                                                    'model' => 'Roadmap',
                                                    'labelColumn' => 'nama_roadmap']],
        'columns' => ['tanggal', 'materi_detail_id', 'user_id', 'status', 'gelombang_id']],
    'jadwal-ujian' => ['model' => 'JadwalUjian',
        'title' => 'Jadwal Ujian',
        'group' => 'Pembelajaran',
        'fields' => [['name' => 'type',
            'label' => 'Jenis ujian',
            'type' => 'select',
            'required' => true,
            'options' => [['value' => 'Harian',
                'label' => 'Harian'], ['value' => 'Pekanan',
                    'label' => 'Pekanan'], ['value' => 'Akhir',
                        'label' => 'Akhir']]], ['name' => 'urutan',
                            'label' => 'Urutan',
                            'type' => 'number',
                            'required' => true], ['name' => 'tanggal',
                                'label' => 'Tanggal',
                                'type' => 'datetime-local',
                                'required' => true], ['name' => 'angkatan_id',
                                    'label' => 'Angkatan',
                                    'type' => 'reference',
                                    'required' => true,
                                    'model' => 'Angkatan',
                                    'labelColumn' => 'kode_angkatan'], ['name' => 'materi_id',
                                        'label' => 'Materi',
                                        'type' => 'reference',
                                        'required' => false,
                                        'model' => 'Materi',
                                        'labelColumn' => 'nama_materi'], ['name' => 'roadmap_id',
                                            'label' => 'Roadmap',
                                            'type' => 'reference',
                                            'required' => false,
                                            'model' => 'Roadmap',
                                            'labelColumn' => 'nama_roadmap'], ['name' => 'gelombang_id',
                                                'label' => 'Gelombang',
                                                'type' => 'reference',
                                                'required' => false,
                                                'model' => 'Gelombang',
                                                'labelColumn' => 'gel']],
        'columns' => ['type', 'urutan', 'tanggal', 'angkatan_id', 'materi_id'],
        'relations' => ['soal' => ['Soal', 'judul']]],
    'ujian' => ['model' => 'Ujian',
        'title' => 'Hasil Ujian',
        'group' => 'Evaluasi',
        'fields' => [['name' => 'user_id',
            'label' => 'Peserta',
            'type' => 'reference',
            'required' => true,
            'model' => 'User',
            'labelColumn' => 'name'], ['name' => 'jenis_ujian_id',
                'label' => 'Jenis ujian',
                'type' => 'reference',
                'required' => false,
                'model' => 'JenisUjian',
                'labelColumn' => 'nama'], ['name' => 'angkatan_id',
                    'label' => 'Angkatan',
                    'type' => 'reference',
                    'required' => false,
                    'model' => 'Angkatan',
                    'labelColumn' => 'kode_angkatan'], ['name' => 'nilai',
                        'label' => 'Nilai',
                        'type' => 'number',
                        'required' => false,
                        'min' => 0,
                        'max' => 100], ['name' => 'nama_ujian',
                            'label' => 'Nama ujian',
                            'type' => 'text',
                            'required' => true], ['name' => 'materi_id',
                                'label' => 'Materi',
                                'type' => 'reference',
                                'required' => true,
                                'model' => 'Materi',
                                'labelColumn' => 'nama_materi'], ['name' => 'keterangan',
                                    'label' => 'Keterangan',
                                    'type' => 'select',
                                    'required' => true,
                                    'options' => [['value' => 'Lulus',
                                        'label' => 'Lulus'], ['value' => 'Tidak Lulus',
                                            'label' => 'Tidak Lulus']]], ['name' => 'kode_ujian',
                                                'label' => 'Kode ujian',
                                                'type' => 'text',
                                                'required' => true], ['name' => 'status',
                                                    'label' => 'Status',
                                                    'type' => 'select',
                                                    'required' => true,
                                                    'options' => [['value' => 'Aktif',
                                                        'label' => 'Aktif'], ['value' => 'Selesai',
                                                            'label' => 'Selesai']]], ['name' => 'nilai_akhir',
                                                                'label' => 'Nilai akhir',
                                                                'type' => 'number',
                                                                'required' => true,
                                                                'min' => 0,
                                                                'max' => 100], ['name' => 'ipk',
                                                                    'label' => 'Ipk',
                                                                    'type' => 'number',
                                                                    'required' => true,
                                                                    'min' => 0,
                                                                    'max' => 4], ['name' => 'predikat',
                                                                        'label' => 'Predikat',
                                                                        'type' => 'text',
                                                                        'required' => false]],
        'columns' => ['user_id', 'materi_id', 'nilai', 'nilai_akhir', 'ipk', 'keterangan']],
    'jawaban' => ['model' => 'SoalUjian',
        'title' => 'Jawaban Peserta',
        'group' => 'Evaluasi',
        'fields' => [['name' => 'soal_id',
            'label' => 'Soal',
            'type' => 'reference',
            'required' => true,
            'model' => 'Soal',
            'labelColumn' => 'judul'], ['name' => 'ujian_id',
                'label' => 'Ujian',
                'type' => 'reference',
                'required' => true,
                'model' => 'Ujian',
                'labelColumn' => 'id'], ['name' => 'user_id',
                    'label' => 'Peserta',
                    'type' => 'reference',
                    'required' => true,
                    'model' => 'User',
                    'labelColumn' => 'name'], ['name' => 'jawaban',
                        'label' => 'Jawaban',
                        'type' => 'text',
                        'required' => true], ['name' => 'istrue',
                            'label' => 'Istrue',
                            'type' => 'checkbox',
                            'required' => false,
                            'default' => true]],
        'columns' => ['soal_id', 'ujian_id', 'user_id', 'jawaban', 'istrue']],
    'kegiatan' => ['model' => 'Kegiatan',
        'title' => 'Kegiatan',
        'group' => 'Aktivitas',
        'fields' => [['name' => 'kategori_id',
            'label' => 'Kategori',
            'type' => 'reference',
            'required' => true,
            'model' => 'KategoriKegiatan',
            'labelColumn' => 'nama'], ['name' => 'type',
                'label' => 'Type',
                'type' => 'select',
                'required' => true,
                'options' => [['value' => 'Umum',
                    'label' => 'Umum'], ['value' => 'Anggota',
                        'label' => 'Anggota']]], ['name' => 'waktu',
                            'label' => 'Waktu kegiatan',
                            'type' => 'datetime-local',
                            'required' => true], ['name' => 'tempat',
                                'label' => 'Tempat',
                                'type' => 'text',
                                'required' => true], ['name' => 'keterangan',
                                    'label' => 'Keterangan',
                                    'type' => 'textarea',
                                    'required' => false]],
        'columns' => ['kategori_id', 'type', 'waktu', 'tempat']],
    'absensi' => ['model' => 'AbsensiKegiatan',
        'title' => 'Absensi Kegiatan',
        'group' => 'Aktivitas',
        'fields' => [['name' => 'user_id',
            'label' => 'Peserta',
            'type' => 'reference',
            'required' => true,
            'model' => 'User',
            'labelColumn' => 'name'], ['name' => 'kegiatan_id',
                'label' => 'Kegiatan',
                'type' => 'reference',
                'required' => true,
                'model' => 'Kegiatan',
                'labelColumn' => 'tempat'], ['name' => 'status_kehadiran',
                    'label' => 'Status kehadiran',
                    'type' => 'select',
                    'required' => true,
                    'options' => [['value' => 'hadir',
                        'label' => 'hadir'], ['value' => 'tidak_hadir',
                            'label' => 'tidak_hadir']]]],
        'columns' => ['user_id', 'kegiatan_id', 'status_kehadiran']],
    'kelompok' => ['model' => 'Group',
        'title' => 'Kelompok',
        'group' => 'Aktivitas',
        'fields' => [['name' => 'nama_group',
            'label' => 'Nama kelompok',
            'type' => 'text',
            'required' => true,
            'max' => 191], ['name' => 'kode_group',
                'label' => 'Kode group',
                'type' => 'text',
                'required' => true]],
        'columns' => ['nama_group', 'kode_group'],
        'relations' => ['users' => ['User', 'name']]],
    'anggota-kelompok' => ['model' => 'GroupUser',
        'title' => 'Anggota Kelompok',
        'group' => 'Aktivitas',
        'fields' => [['name' => 'group_id',
            'label' => 'Kelompok',
            'type' => 'reference',
            'required' => true,
            'model' => 'Group',
            'labelColumn' => 'nama_group'], ['name' => 'user_id',
                'label' => 'Peserta',
                'type' => 'reference',
                'required' => true,
                'model' => 'User',
                'labelColumn' => 'name']],
        'columns' => ['group_id', 'user_id']],
    'kategori-materi' => ['model' => 'KategoriMateri',
        'title' => 'Kategori Materi',
        'group' => 'Konfigurasi',
        'fields' => [['name' => 'nama_kategori',
            'label' => 'Nama kategori',
            'type' => 'text',
            'required' => true,
            'max' => 100]],
        'columns' => ['nama_kategori']],
    'kategori-kegiatan' => ['model' => 'KategoriKegiatan',
        'title' => 'Kategori Kegiatan',
        'group' => 'Konfigurasi',
        'fields' => [['name' => 'nama',
            'label' => 'Nama',
            'type' => 'text',
            'required' => true,
            'max' => 150]],
        'columns' => ['nama']],
    'jenis-ujian' => ['model' => 'JenisUjian',
        'title' => 'Jenis Ujian',
        'group' => 'Konfigurasi',
        'fields' => [['name' => 'nama',
            'label' => 'Nama',
            'type' => 'text',
            'required' => true], ['name' => 'keterangan',
                'label' => 'Keterangan',
                'type' => 'text',
                'required' => false], ['name' => 'waktu',
                    'label' => 'Durasi (menit)',
                    'type' => 'text',
                    'required' => true]],
        'columns' => ['nama', 'keterangan']],
    'jenis-user' => ['model' => 'JenisUser',
        'title' => 'Jenis Pengguna',
        'group' => 'Konfigurasi',
        'fields' => [['name' => 'nama_jenis',
            'label' => 'Nama jenis',
            'type' => 'text',
            'required' => true]],
        'columns' => ['nama_jenis']],
    'struktur' => ['model' => 'Struktur',
        'title' => 'Struktur',
        'group' => 'Konfigurasi',
        'fields' => [['name' => 'nama_struktur',
            'label' => 'Nama struktur',
            'type' => 'text',
            'required' => true,
            'max' => 191]],
        'columns' => ['nama_struktur']],
    'banner' => ['model' => 'Banner',
        'title' => 'Banner',
        'group' => 'Konfigurasi',
        'fields' => [['name' => 'title',
            'label' => 'Judul',
            'type' => 'text',
            'required' => true,
            'max' => 100], ['name' => 'image',
                'label' => 'Image',
                'type' => 'file',
                'required' => true,
                'accept' => 'image/*'], ['name' => 'url',
                    'label' => 'Url',
                    'type' => 'url',
                    'required' => false,
                    'max' => 100], ['name' => 'status',
                        'label' => 'Status',
                        'type' => 'checkbox',
                        'required' => false,
                        'default' => true]],
        'columns' => ['title', 'url', 'status']],
    'halaman' => ['model' => 'Page',
        'title' => 'Halaman Informasi',
        'group' => 'Konfigurasi',
        'fields' => [['name' => 'judul',
            'label' => 'Judul',
            'type' => 'text',
            'required' => true,
            'max' => 191], ['name' => 'slug',
                'label' => 'Slug',
                'type' => 'text',
                'required' => true,
                'max' => 191,
                'unique' => true], ['name' => 'konten',
                    'label' => 'Konten',
                    'type' => 'textarea',
                    'required' => true], ['name' => 'type',
                        'label' => 'Type',
                        'type' => 'select',
                        'required' => true,
                        'options' => [['value' => 'Info',
                            'label' => 'Info'], ['value' => 'FAQ',
                                'label' => 'FAQ'], ['value' => 'Profile',
                                    'label' => 'Profile']]], ['name' => 'image',
                                        'label' => 'Image',
                                        'type' => 'file',
                                        'required' => false,
                                        'accept' => 'image/*'], ['name' => 'is_publish',
                                            'label' => 'Is publish',
                                            'type' => 'checkbox',
                                            'required' => false,
                                            'default' => true], ['name' => 'action_url',
                                                'label' => 'Action url',
                                                'type' => 'url',
                                                'required' => false], ['name' => 'action_label',
                                                    'label' => 'Action label',
                                                    'type' => 'text',
                                                    'required' => false]],
        'columns' => ['judul', 'slug', 'type', 'is_publish', 'action_url']],
    'sertifikat' => ['model' => 'Sertifikat',
        'title' => 'Template Sertifikat',
        'group' => 'Konfigurasi',
        'fields' => [['name' => 'nama',
            'label' => 'Nama',
            'type' => 'text',
            'required' => true,
            'max' => 100], ['name' => 'bg',
                'label' => 'Bg',
                'type' => 'file',
                'required' => true,
                'accept' => 'image/*'], ['name' => 'ttd_nama',
                    'label' => 'Ttd nama',
                    'type' => 'text',
                    'required' => false,
                    'max' => 100], ['name' => 'ttd_jabatan',
                        'label' => 'Ttd jabatan',
                        'type' => 'text',
                        'required' => false,
                        'max' => 100], ['name' => 'ttd_image',
                            'label' => 'Ttd image',
                            'type' => 'file',
                            'required' => false,
                            'accept' => 'image/*'], ['name' => 'ttd_nama2',
                                'label' => 'Ttd nama2',
                                'type' => 'text',
                                'required' => false,
                                'max' => 100], ['name' => 'ttd_jabatan2',
                                    'label' => 'Ttd jabatan2',
                                    'type' => 'text',
                                    'required' => false,
                                    'max' => 100], ['name' => 'ttd_image2',
                                        'label' => 'Ttd image2',
                                        'type' => 'file',
                                        'required' => false,
                                        'accept' => 'image/*'], ['name' => 'status',
                                            'label' => 'Status',
                                            'type' => 'select',
                                            'required' => true,
                                            'options' => [['value' => 'Aktif',
                                                'label' => 'Aktif'], ['value' => 'Tidak Aktif',
                                                    'label' => 'Tidak Aktif']]], ['name' => 'ttd_daftar_nilai',
                                                        'label' => 'Ttd daftar nilai',
                                                        'type' => 'select',
                                                        'required' => true,
                                                        'options' => [['value' => 'default',
                                                            'label' => 'default'], ['value' => 'ttd1',
                                                                'label' => 'ttd1'], ['value' => 'ttd2',
                                                                    'label' => 'ttd2']]]],
        'columns' => ['nama', 'ttd_nama', 'ttd_jabatan', 'ttd_nama2', 'ttd_jabatan2']],
    'jadwal-roadmap' => ['model' => 'JadwalRoadmap',
        'title' => 'Jadwal Roadmap',
        'group' => 'Pembelajaran',
        'fields' => [['name' => 'roadmap_id',
            'label' => 'Roadmap',
            'type' => 'reference',
            'required' => true,
            'model' => 'Roadmap',
            'labelColumn' => 'nama_roadmap'], ['name' => 'gelombang_id',
                'label' => 'Gelombang',
                'type' => 'reference',
                'required' => true,
                'model' => 'Gelombang',
                'labelColumn' => 'gel'], ['name' => 'materi_id',
                    'label' => 'Materi',
                    'type' => 'reference',
                    'required' => true,
                    'model' => 'Materi',
                    'labelColumn' => 'nama_materi'], ['name' => 'group_id',
                        'label' => 'Kelompok',
                        'type' => 'reference',
                        'required' => false,
                        'model' => 'Group',
                        'labelColumn' => 'nama_group'], ['name' => 'judul',
                            'label' => 'Judul',
                            'type' => 'text',
                            'required' => true], ['name' => 'deskripsi',
                                'label' => 'Deskripsi',
                                'type' => 'text',
                                'required' => false], ['name' => 'tanggal_mulai',
                                    'label' => 'Tanggal mulai',
                                    'type' => 'date',
                                    'required' => true], ['name' => 'tanggal_ujian',
                                        'label' => 'Tanggal ujian',
                                        'type' => 'date',
                                        'required' => true], ['name' => 'is_aktif',
                                            'label' => 'Is aktif',
                                            'type' => 'checkbox',
                                            'required' => false,
                                            'default' => true]],
        'columns' => ['judul', 'gelombang_id', 'materi_id', 'tanggal_mulai', 'is_aktif']],
    'sertifikat-peserta' => ['model' => 'SertifikatUser',
        'title' => 'Sertifikat Peserta',
        'group' => 'Evaluasi',
        'fields' => [['name' => 'user_id',
            'label' => 'Peserta',
            'type' => 'reference',
            'required' => true,
            'model' => 'User',
            'labelColumn' => 'name'], ['name' => 'sertifikat_id',
                'label' => 'Template',
                'type' => 'reference',
                'required' => true,
                'model' => 'Sertifikat',
                'labelColumn' => 'nama'], ['name' => 'materi_id',
                    'label' => 'Materi',
                    'type' => 'reference',
                    'required' => true,
                    'model' => 'Materi',
                    'labelColumn' => 'nama_materi'], ['name' => 'ujian_id',
                        'label' => 'Ujian',
                        'type' => 'reference',
                        'required' => false,
                        'model' => 'Ujian',
                        'labelColumn' => 'id'], ['name' => 'predikat',
                            'label' => 'Predikat',
                            'type' => 'text',
                            'required' => true], ['name' => 'tanggal',
                                'label' => 'Tanggal',
                                'type' => 'text',
                                'required' => true], ['name' => 'code',
                                    'label' => 'Code',
                                    'type' => 'text',
                                    'required' => true,
                                    'unique' => true], ['name' => 'ttd_nama',
                                        'label' => 'Ttd nama',
                                        'type' => 'text',
                                        'required' => true], ['name' => 'ttd_jabatan',
                                            'label' => 'Ttd jabatan',
                                            'type' => 'text',
                                            'required' => true], ['name' => 'ttd_image',
                                                'label' => 'Ttd image',
                                                'type' => 'file',
                                                'required' => false,
                                                'accept' => 'image/*'], ['name' => 'ttd_nama2',
                                                    'label' => 'Ttd nama2',
                                                    'type' => 'text',
                                                    'required' => false], ['name' => 'ttd_jabatan2',
                                                        'label' => 'Ttd jabatan2',
                                                        'type' => 'text',
                                                        'required' => false], ['name' => 'ttd_image2',
                                                            'label' => 'Ttd image2',
                                                            'type' => 'file',
                                                            'required' => false,
                                                            'accept' => 'image/*']],
        'columns' => ['user_id', 'sertifikat_id', 'materi_id', 'ujian_id', 'predikat']],
    'gambar-materi' => ['model' => 'MateriDetailImage',
        'title' => 'Gambar Pertemuan',
        'group' => 'Pembelajaran',
        'fields' => [['name' => 'materi_detail_id',
            'label' => 'Pertemuan',
            'type' => 'reference',
            'required' => true,
            'model' => 'MateriDetail',
            'labelColumn' => 'judul'], ['name' => 'image',
                'label' => 'Image',
                'type' => 'file',
                'required' => true,
                'accept' => 'image/*']],
        'columns' => ['materi_detail_id']],
    'kelas' => ['model' => 'Kelas',
        'title' => 'Kelas',
        'group' => 'Pembelajaran',
        'fields' => [['name' => 'nama_kelas',
            'label' => 'Nama kelas',
            'type' => 'text',
            'required' => true], ['name' => 'angkatan_id',
                'label' => 'Angkatan',
                'type' => 'reference',
                'required' => true,
                'model' => 'Angkatan',
                'labelColumn' => 'kode_angkatan'], ['name' => 'admin1',
                    'label' => 'Admin pertama',
                    'type' => 'reference',
                    'required' => false,
                    'model' => 'User',
                    'labelColumn' => 'name'], ['name' => 'admin2',
                        'label' => 'Admin kedua',
                        'type' => 'reference',
                        'required' => false,
                        'model' => 'User',
                        'labelColumn' => 'name']],
        'columns' => ['nama_kelas', 'angkatan_id', 'admin1', 'admin2']],
    'peserta-angkatan' => ['model' => 'AngkatanUser',
        'title' => 'Peserta Angkatan',
        'group' => 'Pembelajaran',
        'fields' => [['name' => 'user_id',
            'label' => 'Peserta',
            'type' => 'reference',
            'required' => true,
            'model' => 'User',
            'labelColumn' => 'name'], ['name' => 'angkatan_id',
                'label' => 'Angkatan',
                'type' => 'reference',
                'required' => true,
                'model' => 'Angkatan',
                'labelColumn' => 'kode_angkatan'], ['name' => 'kelas_id',
                    'label' => 'Kelas',
                    'type' => 'reference',
                    'required' => true,
                    'model' => 'Kelas',
                    'labelColumn' => 'nama_kelas'], ['name' => 'kode_angkatan',
                        'label' => 'Kode angkatan',
                        'type' => 'text',
                        'required' => false], ['name' => 'status',
                            'label' => 'Status',
                            'type' => 'select',
                            'required' => true,
                            'options' => [['value' => 'Aktif',
                                'label' => 'Aktif'], ['value' => 'Lulus',
                                    'label' => 'Lulus'], ['value' => 'DO',
                                        'label' => 'DO']]], ['name' => 'keterangan',
                                            'label' => 'Keterangan',
                                            'type' => 'text',
                                            'required' => false]],
        'columns' => ['user_id', 'angkatan_id', 'kelas_id', 'kode_angkatan', 'status']]];
