import React from 'react';
import { Link, usePage } from '@inertiajs/react';
import Admin2Layout, { Icon } from '../../Layouts/Admin2Layout';

export default function Dashboard({ stats, months, statuses, recent, upcoming }) {
    const { auth } = usePage().props;
    const max = Math.max(...months.map(m => m.value), 1);
    const points = months.map((m,i) => `${40 + i * 96},${190 - m.value/max*150}`).join(' ');
    const total = statuses.reduce((sum,s) => sum + Number(s.value),0);
    const colors = ['#0ea5e9', '#fbbf24', '#22c55e', '#a78bfa'];
    let angle = 0;
    const slices = statuses.map((s,i) => { const start = angle; angle += total ? Number(s.value)/total*100 : 0; return `${colors[i % colors.length]} ${start}% ${angle}%`; });
    return <Admin2Layout title="Dashboard"><div className="page-heading"><div className="page-header"><h2>Selamat datang, {auth.user.name.split(' ')[0]} 👋</h2><p>Pantau perkembangan pembelajaran Bisi Online hari ini.</p></div><span className="date-pill">{new Intl.DateTimeFormat('id-ID', { dateStyle: 'full' }).format(new Date())}</span></div>
        <div className="stats-grid">{stats.map((stat,i) => <Link href={stat.url} className="stat-card" key={stat.label}><div className={`stat-icon stat-color-${i}`}><Icon name={stat.icon} size={24}/></div><div className="stat-label">{stat.label}</div><div className="stat-value">{stat.value.toLocaleString('id-ID')}</div><div className="stat-foot">Lihat selengkapnya <Icon name="arrow" size={14}/></div></Link>)}</div>
        <div className="dashboard-grid"><section className="card"><div className="card-header"><div><h3 className="card-title">Pertumbuhan Peserta</h3><p className="card-subtitle">Pendaftaran baru dalam 6 bulan terakhir</p></div><span className="badge badge-blue">Bulanan</span></div><svg className="growth-chart" viewBox="0 0 560 235" role="img" aria-label={months.map(m => `${m.label}: ${m.value} peserta`).join(', ')}>{[0,1,2,3].map(n => <g key={n}><line x1="40" x2="520" y1={40+n*50} y2={40+n*50} stroke="#f1f5f9"/><text x="30" y={44+n*50} textAnchor="end">{Math.round(max*(3-n)/3)}</text></g>)}<polygon points={`40,190 ${points} 520,190`} fill="#0ea5e9" opacity=".08"/><polyline points={points} fill="none" stroke="#0ea5e9" strokeWidth="2.5" strokeLinejoin="round"/>{months.map((m,i) => <g key={m.label}><circle cx={40+i*96} cy={190-m.value/max*150} r="4" fill="white" stroke="#0ea5e9" strokeWidth="2"><title>{m.label}: {m.value} peserta</title></circle><text x={40+i*96} y="220" textAnchor="middle">{m.label}</text></g>)}</svg></section>
            <section className="card"><div className="card-header"><h3 className="card-title">Status Peserta</h3></div><div className="donut" style={{ background: total ? `conic-gradient(${slices.join(',')})` : '#e2e8f0' }}><div><strong>{total.toLocaleString('id-ID')}</strong><span>Total peserta</span></div></div><div className="chart-legend">{statuses.map((s,i) => <div key={s.label}><span><i style={{ background: colors[i%colors.length] }}/>{s.label}</span><strong>{s.value}</strong></div>)}</div>{!total && <p className="muted">Belum ada peserta terdaftar.</p>}</section></div>
        <div className="dashboard-grid"><section className="card"><div className="card-header"><h3 className="card-title">Peserta Terbaru</h3><Link className="text-link" href="/admin2/peserta">Lihat semua →</Link></div><div className="table-scroll"><table><thead><tr><th>Peserta</th><th>Status</th><th>Bergabung</th></tr></thead><tbody>{recent.map(p => <tr key={p.id}><td><div className="cell-user"><div className="avatar-sm">{p.name.slice(0,2).toUpperCase()}</div><div><Link className="cell-name" href={`/admin2/peserta/${p.id}/edit`}>{p.name}</Link><div className="cell-email">{p.email}</div></div></div></td><td><span className="badge badge-blue">{p.kategori || 'Belum dikategorikan'}</span></td><td>{new Date(p.created_at).toLocaleDateString('id-ID')}</td></tr>)}</tbody></table>{!recent.length && <div className="empty-state">Belum ada peserta.</div>}</div></section>
            <section className="card"><div className="card-header"><h3 className="card-title">Ujian Mendatang</h3><Link className="text-link" href="/admin2/jadwal-ujian">Lihat semua →</Link></div>{upcoming.map(u => <Link className="upcoming-item" href={`/admin2/jadwal-ujian/${u.id}/edit`} key={u.id}><div className="upcoming-icon"><Icon name="calendar"/></div><div><strong>Ujian {u.type}</strong><p>{u.angkatan?.kode_angkatan || 'Tanpa angkatan'}</p><small>{new Date(u.tanggal).toLocaleString('id-ID')}</small></div><Icon name="arrow" size={16}/></Link>)}{!upcoming.length && <div className="empty-state">Belum ada ujian mendatang.</div>}</section></div>
    </Admin2Layout>;
}
