import React from 'react';
import { Link, useForm } from '@inertiajs/react';
import Admin2Layout from '../../Layouts/Admin2Layout';
import { Reference } from './Fields';

export default function Reports({ kind, filters, records }) {
    const activity = kind === 'activity';
    const title = activity ? 'Keaktifan Peserta' : 'Link Materi Harian';
    const base = activity ? '/admin2/keaktifan-peserta' : '/admin2/link-materi-harian';
    const form = useForm(filters);
    return <Admin2Layout title={title}><div className="page-header"><h2>{title}</h2><p>{activity ? 'Peserta dengan jumlah ujian dalam periode yang dipilih di bawah atau sama dengan batas.' : 'Tautan pembelajaran untuk tanggal yang dipilih.'}</p></div><section className="card"><form className="filter-grid" onSubmit={e => { e.preventDefault(); form.get(base); }}>{activity ? <><label>Dari tanggal<input required type="date" value={form.data.start} onChange={e => form.setData('start',e.target.value)}/></label><label>Sampai tanggal<input required type="date" value={form.data.end} onChange={e => form.setData('end',e.target.value)}/></label><label>Maksimal jumlah ujian<input type="number" min="0" value={form.data.maximum} onChange={e => form.setData('maximum',e.target.value)}/></label><label>Angkatan<Reference url="/admin2/ujian/options/angkatan_id" value={form.data.angkatan} onChange={v => form.setData('angkatan',v)}/></label></> : <label>Tanggal<input required type="date" value={form.data.date} onChange={e => form.setData('date',e.target.value)}/></label>}<div className="heading-actions"><button className="btn btn-primary" disabled={form.processing}>Tampilkan</button>{activity && <a className="btn btn-outline" href={`${base}?${new URLSearchParams({...filters,export:1})}`}>Ekspor CSV</a>}</div></form>{Object.values(form.errors).map((error,i) => <p key={i} className="field-error">{error}</p>)}<div className="table-scroll report-table"><table><thead><tr>{(activity ? ['Nama','Email','Telepon','Jumlah ujian'] : ['Pertemuan','Materi','Gelombang','Tautan']).map(h => <th key={h}>{h}</th>)}</tr></thead><tbody>{records.data.map(row => <tr key={row.id}>{activity ? <><td>{row.name}</td><td>{row.email}</td><td>{row.no_hp || '—'}</td><td>{row.ujian_count}</td></> : <><td>{row.title}</td><td>{row.materi}</td><td>{row.gelombang || '—'}</td><td>{row.url ? <a className="text-link" href={row.url} target="_blank" rel="noreferrer">Buka materi ↗</a> : 'Belum tersedia'}</td></>}</tr>)}</tbody></table></div>{!records.data.length && <div className="empty-state">Tidak ada data untuk filter ini.</div>}<div className="table-bottom"><span>{records.total} data</span><div className="pagination">{records.prev_page_url && <Link className="btn btn-outline" href={records.prev_page_url}>Sebelumnya</Link>}{records.next_page_url && <Link className="btn btn-outline" href={records.next_page_url}>Berikutnya</Link>}</div></div></section></Admin2Layout>;
}
